reporter: com.uber.profiling.reporters.InfluxDBOutputReporter
tag: DurationProfileExample
metricInterval: 1000
durationProfiling: com.uber.profiling.examples.*
sampleInterval: 100
influxdb.host: localhost
influxdb.port: 8086
influxdb.database: profiling
influxdb.username:
influxdb.password: