{
 "title": "Java Application Profiling",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "executorProcessUuid",
    "query": "show tag values from Stacktrace with key = \"processUuid\""
   },
   {
    "name": "service_tag",
    "label": "Service",
    "query": "show tag values with key=\"tag\""
   },
   {
    "name": "method",
    "label": "Method Name",
    "query": "show tag values with key=\"method\""
   },
   {
    "name": "class",
    "label": "Class Name",
    "query": "show tag values with key=\"class\""
   },
   {
    "name": "host",
    "label": "Host",
    "query": "show tag values with key=\"host\""
   },
   { "name": "aggregation", "label": "Aggregation", "query": "10s,20s,30s,1m,2m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Method Duration over Time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(metricValue) FROM MethodDuration WHERE \"processUuid\" =~ /^$executorProcessUuid$/ AND \"metricName\"='duration.sum' and \"tag\"=~ /^$service_tag$/  and \"host\"=~ /^$host$/ and \"methodName\"=~ /^$method$/ and \"class\"=~ /^$class$/ and $timeFilter group by time($aggregation), method fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor IO",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "$tag_method; $tag_class",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(metricValue) FROM MethodDuration WHERE \"processUuid\" =~ /^$executorProcessUuid$/ AND \"metricName\"='duration.sum' and \"tag\"=~ /^$service_tag$/ and \"host\"=~ /^$host$/ and \"methodName\"=~ /^$method$/ and \"class\"=~ /^$class$/ and $timeFilter group by method,* fill(none) order by asc slimit 10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor IO",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "alias": "$tag_method; $tag_class",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(metricValue) FROM MethodDuration WHERE \"processUuid\" =~ /^$executorProcessUuid$/ AND \"metricName\"='duration.count' and \"tag\"=~ /^$service_tag$/ and \"host\"=~ /^$host$/ and \"methodName\"=~ /^$method$/ and \"class\"=~ /^$class$/ and $timeFilter group by method,* fill(none) order by asc slimit 10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stacktrace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stacktrace",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": " select sum(count) from Stacktrace where  \"processUuid\" =~ /^$executorProcessUuid$/ and \"stacktrace\"=~ /$method/ and  \"stacktrace\"=~ /$class/ AND stacktrace != '' and $timeFilter and \"tag\"=~ /^$service_tag$/ and \"host\"=~ /^$host$/ group by stack",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JAVA metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "System CPU Load",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 41 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"systemCpuLoad\" as \"System CPU\" from \"CpuAndMemory\"  where \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Driver Current Process CPU Load",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 6, "y": 41 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"processCpuLoad\" as process from \"CpuAndMemory\"  where \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Executor Current Heap Used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 12, "y": 41 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"heapMemoryTotalUsed\" as Used from \"CpuAndMemory\"  where  \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Driver Current Heap Used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 41 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"heapMemoryTotalUsed\" as Used from \"CpuAndMemory\" where  \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Heap Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Total Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"heapMemoryTotalUsed\" from CpuAndMemory where  \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Total Commited",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"heapMemoryCommitted\" from CpuAndMemory where \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Non Heap Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Total Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"nonHeapMemoryTotalUsed\" from CpuAndMemory where \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Total Commited",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"nonHeapMemoryCommitted\" from CpuAndMemory where \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Driver GC Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"gc-PSMarkSweep-collectionCount\" from CpuAndMemory where \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Executor Heap Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"memoryPools-PSEdenSpace-usageUsed\" as EdenSpace, \"memoryPools-PSSurvivorSpace-usageUsed\" as  SurvivorSpace, \"memoryPools-TenuredGen-usageUsed\" as  TenuredGen from \"CpuAndMemory\"  where \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Executor Non-Heap Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"memoryPools-CodeCache-usageUsed\" as CodeCache, \"memoryPools-CompressedClassSpace-usageUsed\" as  CompressedClassSpace, \"memoryPools-Metaspace-usageUsed\" as  Metaspace from \"CpuAndMemory\"  where  \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Executor GC Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"gc-PSScavenge-collectionTime \" as Cavenge, \"gc-PSMarkSweep-collectionTime\" as  MarkSweep from \"CpuAndMemory\"  where \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Executor Committed And Used Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"heapMemoryCommitted\" as Committed, \"heapMemoryTotalUsed\" as Used from \"CpuAndMemory\"  where   \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Driver Committed and Used Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 64 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"heapMemoryCommitted\" as Committed, \"heapMemoryTotalUsed\" as Used from \"CpuAndMemory\"  where  \"processUuid\" =~ /^$executorProcessUuid$/ AND  $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Executor Direct Buffer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 64 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select \"bufferPools-direct-memoryUsed\" as Used, \"bufferPools-direct-totalCapacity\" as  Capacity from \"CpuAndMemory\"  where \"processUuid\" =~ /^$executorProcessUuid$/ AND  \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}